import { Cardpack } from "@src/types/shop/cardpack.type";

export const cardpackDummy: Cardpack[] = [
  {
    cardpackId: 1,
    cardpackName: "삼국시대 유물팩",
    cardpackContent: "고구려·백제·신라의 무기와 예술품을 담은 카드팩",
    price: 500,
    storeType: "REGION",
  },
  {
    cardpackId: 2,
    cardpackName: "조선 왕실 보물팩",
    cardpackContent: "조선 왕실에서 사용된 도자기, 어보, 의복이 담긴 카드팩",
    price: 800,
    storeType: "REGION",
  },
  {
    cardpackId: 3,
    cardpackName: "불교 문화 유산팩",
    cardpackContent: "팔만대장경과 불상, 탑 등 불교 문화의 정수를 모은 카드팩",
    price: 700,
    storeType: "REGION",
  },
  {
    cardpackId: 4,
    cardpackName: "독립운동 유물팩",
    cardpackContent: "일제강점기 독립운동가들의 기록과 유물을 모은 카드팩",
    price: 600,
    storeType: "REGION",
  },
  {
    cardpackId: 5,
    cardpackName: "전통 생활 도구팩",
    cardpackContent: "선조들의 지혜가 담긴 농기구와 생활 도구를 모은 카드팩",
    price: 400,
    storeType: "REGION",
  },
  {
    cardpackId: 6,
    cardpackName: "고려 청자팩",
    cardpackContent: "비취빛 고려 청자와 불교 관련 유물을 담은 카드팩",
    price: 750,
    storeType: "REGION",
  },
  {
    cardpackId: 7,
    cardpackName: "훈민정음 유산팩",
    cardpackContent: "세종대왕이 창제한 훈민정음과 관련 기록을 모은 카드팩",
    price: 900,
    storeType: "REGION",
  },
  {
    cardpackId: 8,
    cardpackName: "전쟁 유물팩",
    cardpackContent: "삼국·조선의 전쟁에서 쓰인 무기와 방어구를 모은 카드팩",
    price: 550,
    storeType: "REGION",
  },
  {
    cardpackId: 9,
    cardpackName: "궁궐 건축팩",
    cardpackContent: "경복궁, 창덕궁 등 조선 궁궐의 건축 유산을 담은 카드팩",
    price: 650,
    storeType: "REGION",
  },
  {
    cardpackId: 10,
    cardpackName: "민속 문화팩",
    cardpackContent: "탈춤, 농악, 민속 놀이와 관련된 전통 유물을 모은 카드팩",
    price: 450,
    storeType: "REGION",
  },
  {
    cardpackId: 11,
    cardpackName: "무속 신앙팩",
    cardpackContent: "굿과 신앙에서 사용된 무속 도구와 상징물을 담은 카드팩",
    price: 500,
    storeType: "REGION",
  },
  {
    cardpackId: 12,
    cardpackName: "전통 의복팩",
    cardpackContent: "한복, 관복 등 전통 의복과 장신구를 모은 카드팩",
    price: 600,
    storeType: "REGION",
  },
  {
    cardpackId: 13,
    cardpackName: "고대 금속공예팩",
    cardpackContent: "금관, 장신구 등 정교한 금속공예품을 담은 카드팩",
    price: 850,
    storeType: "REGION",
  },
  {
    cardpackId: 14,
    cardpackName: "고분 유물팩",
    cardpackContent: "신라 천마총 등 고분에서 출토된 다양한 유물을 모은 카드팩",
    price: 700,
    storeType: "REGION",
  },
  {
    cardpackId: 15,
    cardpackName: "현대사 기념팩",
    cardpackContent: "대한민국 건국과 근현대사의 기념품을 담은 카드팩",
    price: 500,
    storeType: "REGION",
  },
];
