import { Card } from "@src/types/card/card.type";

export const courseDummy = [
  {
    courseId: 1,
    name: "안동 2025 코스",
    thumbnail:
      "https://pbs.twimg.com/media/EbbB8FqU0AAIAf9?format=jpg&name=4096x4096",
    creator: "박재민",
    tag: ["안동", "하회마을"],
    description: "2025 개정된 안동 최고의 여행지 코스입니다.",
    heartCount: 1024,
    clearCount: 190,
    eventId: 1,
    isClear: true,
    isHeart: true,
    clearRuinsCount: 3,
    maxRuinsCount: 6,
  },
  {
    courseId: 2,
    name: "무녀 2025 코스",
    thumbnail:
      "https://img2.sbs.co.kr/img/seditor/VD/2024/10/10/2NL1728533264795-640-0.jpg",
    creator: "김은찬",
    tag: ["무녀", "예쁜 누나"],
    description: "2025 개정된 안동 최고의 여행지 코스입니다.",
    heartCount: 385,
    clearCount: 10,
    eventId: null,
    isClear: false,
    isHeart: false,
    clearRuinsCount: 2,
    maxRuinsCount: 9,
  },
  {
    courseId: 3,
    name: "무녀 2025 코스",
    thumbnail:
      "https://mblogthumb-phinf.pstatic.net/MjAyMjA5MDdfODEg/MDAxNjYyNDg1NzkyMjI1.2F3qxH1se8ZO2aByObOXmnjdqj9e1hbps0DEThLKlewg.qTvS2a_x3WyE7KHBMa9hT-s2MwB-fepGk_MZALIZoSog.JPEG.niceguy00/Seul%EC%BB%B4_%EC%95%84%EC%9D%B4%EB%B8%8C_AfterLIKE_%EC%9B%90%EC%98%8152.jpg?type=w800",
    creator: "김은찬",
    tag: ["무녀", "예쁜 누나"],
    description: "2025 개정된 안동 최고의 여행지 코스입니다.",
    heartCount: 1000,
    clearCount: 798,
    eventId: null,
    isClear: true,
    isHeart: true,
    clearRuinsCount: 3,
    maxRuinsCount: 7,
  },
  {
    courseId: 5,
    name: "히메냥의 판타지 코스",
    thumbnail:
      "https://mblogthumb-phinf.pstatic.net/MjAyMjA4MjZfNDAg/MDAxNjYxNDk4MDg4NDM1.StL53Tj5CV8iyOYs-N6zWC5QQ7ypfDyQMTmsyq0n2_4g.f440mSwQrleS_Tlri1gpVTLzAAj50fP_KdQsCp_HFSAg.JPEG.niceguy00/Seul%EC%BB%B4_%EB%89%B4%EC%A7%84%EC%8A%A4_%EC%96%B4%ED%85%90%EC%85%98_%ED%95%B4%EB%A6%B0162.jpg?type=w800", // 업로드된 이미지 경로
    creator: "히메냥",
    tag: ["몽환", "고양이", "판타지"],
    description:
      "이세계에서 만나는 고양이 여왕과의 하루. 현실에서 벗어난 몽환 여행.",
    heartCount: 814,
    clearCount: 314,
    eventId: 6,
    isClear: true,
    isHeart: false,
    clearRuinsCount: 1,
    maxRuinsCount: 9,
  },
  {
    courseId: 4,
    name: "제주 감성 드라이브",
    thumbnail:
      "https://dimg.donga.com/egc/CDB/VODA/Article/C01/B120041702/62/04/e8/b4/6204e8b40dd3a0a0a0a.jpg",
    creator: "최유정",
    tag: ["제주", "감성", "드라이브"],
    description: "제주의 드라이브 명소를 감성 있게 묶은 추천 코스.",
    heartCount: 642,
    clearCount: 89,
    eventId: 2,
    isClear: false,
    isHeart: true,
    clearRuinsCount: 8,
    maxRuinsCount: 10,
  },
  {
    courseId: 9,
    name: "최예나 팬 싸인회",
    thumbnail:
      "https://i.ytimg.com/vi/-jeUhW3U7pQ/hq720.jpg?sqp=-oaymwEhCK4FEIIDSFryq4qpAxMIARUAAAAAGAElAADIQj0AgKJD&rs=AOn4CLBvazG0TnpXHTrpL_UrQXkWXFIQHA",
    creator: "최유정",
    tag: ["제주", "감성", "드라이브"],
    description: "제주의 드라이브 명소를 감성 있게 묶은 추천 코스.",
    heartCount: 642,
    clearCount: 89,
    eventId: 2,
    isClear: false,
    isHeart: true,
    clearRuinsCount: 8,
    maxRuinsCount: 10,
  },
  {
    courseId: 10,
    name: "최예나 직캠 관람회",
    thumbnail:
      "https://i.ytimg.com/vi/0sopSHZ0968/hq720.jpg?sqp=-oaymwEhCK4FEIIDSFryq4qpAxMIARUAAAAAGAElAADIQj0AgKJD&rs=AOn4CLAr7gqRQKho2NV0z64rrIyNiUajHA",
    creator: "최유정",
    tag: ["제주", "감성", "드라이브"],
    description: "제주의 드라이브 명소를 감성 있게 묶은 추천 코스.",
    heartCount: 642,
    clearCount: 89,
    eventId: 2,
    isClear: false,
    isHeart: true,
    clearRuinsCount: 8,
    maxRuinsCount: 10,
  },
];

export const cardDummy: Card = {
  cardId: 1,
  cardName: "최예나",
  cardImageUrl:
    "https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcQ2VDmx68oASUiM4HiJmmz5WR7nn8SSz5sJ18zXot0EOU_rGtAp8wWyt4r5J2ook_HU6_oEb9Ei0nSA674XMHqA3A",
  cardType: "SHINING_CARD",
  regionAttributeName: "경기",
  nationAttributeName: "대한민국",
  lineAttributeName: "신앙",
  isAtv: false,
  size: "S",
};
