import { CardResponse } from "@src/types/card/card.type";

export const DUM_DECK: CardResponse[][] = [
  [
    {
      cardId: 1,
      name: "대구소프트웨어마이스터고등학교",
      imageUrl: "",
      cardType: "BASIC_CARD",
      nationAttributeName: "대한민국",
      lineAttributeName: "학문",
      regionAttributeName: "경북",
    },
    {
      cardId: 2,
      name: "경북소프트웨어마이스터고등학교",
      imageUrl: "",
      cardType: "BASIC_CARD",
      nationAttributeName: "대한민국",
      lineAttributeName: "학문",
      regionAttributeName: "경북",
    },
    {
      cardId: 3,
      name: "부산소프트웨어마이스터고등학교",
      imageUrl: "",
      cardType: "BASIC_CARD",
      nationAttributeName: "대한민국",
      lineAttributeName: "학문",
      regionAttributeName: "경남",
    },
    {
      cardId: 4,
      name: "대덕소프트웨어마이스터고등학교",
      imageUrl: "",
      cardType: "BASIC_CARD",
      nationAttributeName: "대한민국",
      lineAttributeName: "학문",
      regionAttributeName: "전북",
    },
    {
      cardId: 5,
      name: "광주소프트웨어마이스터고등학교",
      imageUrl: "",
      cardType: "BASIC_CARD",
      nationAttributeName: "대한민국",
      lineAttributeName: "학문",
      regionAttributeName: "전남",
    },
    {
      cardId: 6,
      name: "한국디지털미디어고등학교",
      imageUrl: "",
      cardType: "BASIC_CARD",
      nationAttributeName: "대한민국",
      lineAttributeName: "학문",
      regionAttributeName: "경북",
    },
    {
      cardId: 7,
      name: "경기게임마이스터고등학교",
      imageUrl: "",
      cardType: "BASIC_CARD",
      nationAttributeName: "대한민국",
      lineAttributeName: "학문",
      regionAttributeName: "경기",
    },
  ],
  [
    {
      cardId: 8,
      name: "첨성대",
      imageUrl: "",
      cardType: "BASIC_CARD",
      nationAttributeName: "신라",
      lineAttributeName: "기술",
      regionAttributeName: "경북",
    },
    {
      cardId: 9,
      name: "불국사",
      imageUrl: "",
      cardType: "BASIC_CARD",
      nationAttributeName: "통일신라",
      lineAttributeName: "신앙",
      regionAttributeName: "경북",
    },
    {
      cardId: 10,
      name: "황룡사지",
      imageUrl: "",
      cardType: "BASIC_CARD",
      nationAttributeName: "신라",
      lineAttributeName: "신앙",
      regionAttributeName: "경북",
    },
    {
      cardId: 11,
      name: "석굴암",
      imageUrl: "",
      cardType: "BASIC_CARD",
      nationAttributeName: "통일신라",
      lineAttributeName: "신앙",
      regionAttributeName: "경북",
    },
    {
      cardId: 12,
      name: "분황사",
      imageUrl: "",
      cardType: "BASIC_CARD",
      nationAttributeName: "신라",
      lineAttributeName: "신앙",
      regionAttributeName: "경북",
    },
    {
      cardId: 13,
      name: "문무대왕릉",
      imageUrl: "",
      cardType: "BASIC_CARD",
      nationAttributeName: "통일신라",
      lineAttributeName: "역사",
      regionAttributeName: "경북",
    },
    {
      cardId: 14,
      name: "경주 석빙고",
      imageUrl: "",
      cardType: "BASIC_CARD",
      nationAttributeName: "조선",
      lineAttributeName: "기술",
      regionAttributeName: "경북",
    },
  ],
  [
    {
      cardId: 15,
      name: "남한산성",
      imageUrl: "",
      cardType: "BASIC_CARD",
      nationAttributeName: "조선",
      lineAttributeName: "기술",
      regionAttributeName: "경기",
    },
    {
      cardId: 16,
      name: "공산성",
      imageUrl: "",
      cardType: "BASIC_CARD",
      nationAttributeName: "백제",
      lineAttributeName: "체제",
      regionAttributeName: "전남",
    },
    {
      cardId: 17,
      name: "부여 왕릉원",
      imageUrl: "",
      cardType: "BASIC_CARD",
      nationAttributeName: "백제",
      lineAttributeName: "상징",
      regionAttributeName: "전남",
    },
    {
      cardId: 18,
      name: "미륵사지",
      imageUrl: "",
      cardType: "BASIC_CARD",
      nationAttributeName: "백제",
      lineAttributeName: "신앙",
      regionAttributeName: "전북",
    },
  ]
]